---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - ./pvc.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: qbittorrent-config
    files:
      - categories.json
      - qBittorrent.conf
generatorOptions:
  disableNameSuffixHash: true
