apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - intel-device-plugin/ks.yaml
  - node-feature-discovery/ks.yaml
  - metrics-server/ks.yaml
  - cilium/ks.yaml
  - local-path-provisioner/ks.yaml
  - nvidia-device-plugin/ks.yaml
