---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-superuser.yaml
  - postgres-apps-user.yaml
  - postgres-apps-elevated.yaml
  - postgres-windmill-user.yaml
  - postgres-cluster.yaml
  - windmill-database.yaml
