---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-superuser.yaml
  - postgres-windmill-user.yaml
  - postgres-home-assistant-user.yaml
  - postgres-luncherbox-user.yaml
# - postgres-cluster.yaml
