---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-old-superuser-secret.yaml
  - postgres-superuser-secret.yaml
  - postgres-windmill-user-secret.yaml
  - postgres-home-assistant-user-secret.yaml
  - postgres-luncherbox-user-secret.yaml
  - postgres-cluster.yaml
  - databases.yaml
