---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - pvc.yaml
  - secret.yaml
configMapGenerator:
  - name: home-assistant-config
    files:
      - configuration.yaml=../config/configuration.yaml
generatorOptions:
  disableNameSuffixHash: true
