---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - envoy-gateway/operator/ks.yaml
  - envoy-gateway/ks.yaml
  - external-dns/external/ks.yaml
  - external-dns/internal/ks.yaml