apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app-template.yaml
  - anby/ks.yaml
  - autobrr/ks.yaml
  - coder/ks.yaml
  - flaresolverr/ks.yaml
  - pgadmin/ks.yaml
  - plex/ks.yaml
  - pocket-id/ks.yaml
  - prowlarr/ks.yaml
  - qbittorrent/ks.yaml
  - qui/ks.yaml
  - tautulli/ks.yaml
  - windmill/ks.yaml
  - netronome/ks.yaml
  - podinfo/ks.yaml
  - steam-gateway/ks.yaml
  - home-assistant/ks.yaml
  - shared/redis/ks.yaml
  - shared/postgres/ks.yaml
  - luncher-box/backend/ks.yaml
  - luncher-box/frontend/ks.yaml
  - zot/ks.yaml
