apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app-template.yaml
  - plex/ks.yaml
  - windmill/ks.yaml
  - podinfo/ks.yaml
  - steam-gateway/ks.yaml
